name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Yadaa
        uses: gautamkrishnar/blog-post-workflow@master
        with: #parsing rss feeds
          max_post_count: "6"
          user_agent: "gh-actions-profile"
          remove_duplicates: true
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYzocrbgFApPAGhq7PAw9Gw,https://aviparshan.medium.com/feed,https://sales.aviparshan.com/feeds/posts/default?alt=rss,https://tech.aviparshan.com/feeds/posts/default?alt=rss,https://www.youtube.com/feeds/videos.xml?channel_id=UCxSsckr_q-SfZ7lkoh2dVCQ,https://cs.aviparshan.com/atom.xml"
